name: OpenSSF Scorecard (local test)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 0' # Every Sunday at 01:00 UTC

permissions:
  contents: read
  security-events: write

jobs:
  scorecard:
    name: Run OpenSSF Scorecard
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Scorecard (SARIF format for security tab)
        uses: ossf/scorecard-action@v2.4.1
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: false

      - name: Upload SARIF file to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

      - name: Run Scorecard (SARIF format for security tab)
        uses: ossf/scorecard-action@v2.4.1
        with:
          results_file: results.json
          results_format: json
          publish_results: false

      - name: Upload Scorecard JSON results
        uses: actions/upload-artifact@v4
        with:
          name: scorecard-results
          path: results.json
